version: "3.9"

services:
  database:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: foodcourt_db
      #MARIADB_USER: louan
      #MARIADB_PASSWORD: MARIADB_PASSWORD
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 1s
      timeout: 1s
      retries: 20

  back-foodcourt:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - "8097:8097"
    depends_on:
      database:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - 1333:8080

volumes:
  db_data:
