version: "3.9"

services:
  database:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: foodcourt_db
      # MARIADB_USER: root
      #MARIADB_PASSWORD: MARIADB_PASSWORD
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 1s
      timeout: 1s
      retries: 20

  back-foodcourt:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - "8095:8095"
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_HOST=database:3306
      - DB_NAME=foodcourt_db
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EMAIL_FROM=${SMTP_USER}
      - TEMPLATE_PATH=/app/app/templates
    depends_on:
      database:
        condition: service_healthy

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    container_name: mercure_foodcourt
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ":80"
      MERCURE_PUBLISHER_JWT_KEY: "8c1f0ba78cabd4ea856a4945f9ec94f7ddbaecca3315ab52d175c3a47415dcfb"
      MERCURE_SUBSCRIBER_JWT_KEY: "8c1f0ba78cabd4ea856a4945f9ec94f7ddbaecca3315ab52d175c3a47415dcfb"
      MERCURE_EXTRA_DIRECTIVES: cors_origins "*" #cors_origins "*"
    ports:
      - "9090:80"
      - "443:443"

  adminer:
    image: adminer
    restart: always
    ports:
      - 1333:8080

volumes:
  db_data:
